# Appveyor should automatically run the tests.
# For configuration options, visit: https://www.appveyor.com/docs/running-tests
install:
  # set JAVA_HOME path to JDK 1.7
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.7.0

  # set PATH
  - SET PATH=C:\google\google-cloud-sdk\bin;C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%

  # check Java version
  - java -version

  # install Maven
  - appveyor DownloadFile http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip
  - 7z x apache-maven-3.2.5-bin.zip -oC:\maven

build_script:
  - mvn clean install -DskipTests -B -U

test_script:
  - mvn test